name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/Group-9-MERN
            git pull origin main
            echo "VITE_API_URL=https://medspace.dev" > frontend/.env
            npm install --prefix backend
            npm install --prefix frontend
            npm run build --prefix frontend
            pm2 restart group9-api --update-env
